# Generated by Django 3.2.2 on 2021-05-31 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='driver_status',
            new_name='driver_busy',
        ),
    ]
