# Generated by Django 3.2.2 on 2021-05-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=100, verbose_name='Імя і прізвище водія')),
                ('car', models.CharField(max_length=100, verbose_name='Автомобіль водія')),
                ('Numb_car', models.CharField(max_length=8, verbose_name='Номерний знак авто')),
                ('driver_status', models.BooleanField(default=False, verbose_name='Статус водія')),
                ('complete_order', models.IntegerField(verbose_name='Кількість виконаних замовлень')),
            ],
        ),
    ]
