# Generated by Django 3.2.2 on 2021-05-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='full_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.IntegerField(verbose_name='ID водія')),
                ('start', models.TextField(verbose_name='Кординати початку')),
                ('finish', models.TextField(verbose_name='Кінцеві кординати')),
                ('distance', models.FloatField(verbose_name='Відстань від початку до кінця')),
                ('price', models.FloatField()),
                ('time_order', models.DateTimeField(verbose_name='Час подання заявки')),
                ('time_order_accepted', models.DateTimeField(verbose_name='Час прийняття замовлення')),
                ('time_order_finished', models.DateTimeField(verbose_name='Час виконання замовлення')),
                ('in_process', models.BooleanField(default=False, verbose_name='Статус замовлення')),
                ('completed', models.BooleanField(default=False, verbose_name='Виконане замовлення')),
            ],
        ),
    ]
