# Generated by Django 3.2.2 on 2021-05-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('full_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='full_info',
            name='time_order_finished',
            field=models.DateTimeField(null=True, verbose_name='Час виконання замовлення'),
        ),
    ]
