# Generated by Django 3.2.2 on 2021-05-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TextField(verbose_name='Кординати початку')),
                ('finish', models.TextField(verbose_name='Кінцеві кординати')),
                ('distance', models.FloatField(verbose_name='Відстань від початку до кінця')),
                ('price', models.FloatField()),
                ('time_order', models.DateTimeField(verbose_name='Час подання заявки')),
            ],
        ),
    ]
